In [1]:
import pandas as pd
df = pd.read_csv("titanic_train.csv", index_col="PassengerId")
# Git saved my life
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [2]:
df["CabinDeck"] = df["Cabin"].str[0]
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,CabinDeck
PassengerId,,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,B
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [3]:
df["Ticket"].value_counts()

Ticket
347082             7
1601               7
CA. 2343           7
3101295            6
CA 2144            6
                  ..
SOTON/OQ 392076    1
211536             1
112053             1
111369             1
392091             1
Name: count, Length: 681, dtype: int64

In [4]:
df["Title"] = df["Name"].str.extract(r',\s*([^\.]+)\.')
title_survival = df.groupby("Title")["Survived"].mean().sort_values()
title_survival

Title
Capt            0.000000
Don             0.000000
Jonkheer        0.000000
Rev             0.000000
Mr              0.156673
Dr              0.428571
Col             0.500000
Major           0.500000
Master          0.575000
Miss            0.697802
Mrs             0.792000
Lady            1.000000
Mme             1.000000
Mlle            1.000000
Ms              1.000000
Sir             1.000000
the Countess    1.000000
Name: Survived, dtype: float64

In [5]:
df["Title"].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [6]:
df["Title"] = df["Title"].replace({"Mlle": "Miss", "Mme": "Mrs", "Ms": "Miss"})
high_status = ["the Countess", "Sir", "Lady", "Don", "Dona", "Jonkheer"]
above_average_title = ["Dr", "Major", "Col"]
hardcore_mfs = ["Capt", "Rev"]
df["Title"] = df["Title"].replace(high_status, "High Status")
df["Title"] = df["Title"].replace(above_average_title, "Improved Status")
df["Title"] = df["Title"].replace(hardcore_mfs, "Mr")
title_survival = df.groupby("Title")["Survived"].mean().sort_values()
title_survival

Title
Mr                 0.154580
Improved Status    0.454545
Master             0.575000
High Status        0.600000
Miss               0.702703
Mrs                0.793651
Name: Survived, dtype: float64

In [7]:
test = pd.read_csv("titanic_test.csv")
test["Title"] = test["Name"].str.extract(r',\s*([^\.]+)\.')
test["Title"] = test["Title"].replace({"Mlle": "Miss", "Mme": "Mrs", "Ms": "Miss"})
high_status = ["the Countess", "Sir", "Lady", "Don", "Dona", "Jonkheer"]
above_average_title = ["Dr", "Major", "Col"]
hardcore_mfs = ["Capt", "Rev"]
test["Title"] = test["Title"].replace(high_status, "High Status")
test["Title"] = test["Title"].replace(above_average_title, "Improved Status")
test["Title"] = test["Title"].replace(hardcore_mfs, "Mr")
print(test["Title"].unique())
print(test["Title"].value_counts())

['Mr' 'Mrs' 'Miss' 'Master' 'Improved Status' 'High Status']
Title
Mr                 242
Miss                79
Mrs                 72
Master              21
Improved Status      3
High Status          1
Name: count, dtype: int64

In [8]:
title_map = {title: i for i, title in enumerate(title_survival.index)}
title_map

{'Mr': 0,
 'Improved Status': 1,
 'Master': 2,
 'High Status': 3,
 'Miss': 4,
 'Mrs': 5}

In [9]:
df["Title_encoded"] = df["Title"].map(title_map)
test["Title_encoded"] = test["Title"].map(title_map)
df[["Title", "Title_encoded"]].head(10)

              Title  Title_encoded
PassengerId
1                Mr              0
2               Mrs              5
3              Miss              4
4               Mrs              5
5                Mr              0
6                Mr              0
7                Mr              0
8            Master              2
9               Mrs              5
10              Mrs              5

In [10]:
gender_map = {"male": 0, "female": 1}
df["Gender_encoded"] = df["Sex"].map(gender_map)

In [11]:
bins = [0, 12, 18, 35, 60, 80]
labels = ["Child", "Teen", "Adult", "Middle-Aged", "Senior"]

df["AgeGroup"] = pd.cut(df["Age"], bins=bins, labels=labels)

age_survival = df.groupby("AgeGroup")["Survived"].mean().sort_values(ascending=False)
age_survival

C:\Users\70821\AppData\Local\Temp\ipykernel_20412\1520611729.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_survival = df.groupby("AgeGroup")["Survived"].mean().sort_values(ascending=False)

AgeGroup
Child          0.579710
Teen           0.428571
Middle-Aged    0.400000
Adult          0.382682
Senior         0.227273
Name: Survived, dtype: float64

In [12]:
df["TotalFamily"] = df["SibSp"] + df["Parch"]
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,CabinDeck,Title,Title_encoded,Gender_encoded,AgeGroup,TotalFamily
PassengerId,,,,,,,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN,Mr,0,0,Adult,1
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,Mrs,5,1,Middle-Aged,1
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN,Miss,4,1,Adult,0
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C,Mrs,5,1,Adult,1
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN,Mr,0,0,Adult,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN,Mr,0,0,Adult,0
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,B,Miss,4,1,Adult,0
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN,Miss,4,1,NaN,3
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,C,Mr,0,0,Adult,0
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN,Mr,0,0,Adult,0

In [13]:
df["FamilyGroup"] = "Very Large"
df.loc[df["TotalFamily"] == 0, "FamilyGroup"] = "Alone"
df.loc[(df["TotalFamily"] > 0) & (df["TotalFamily"] <= 3), "FamilyGroup"] = "Small"
df.loc[(df["TotalFamily"] > 3) & (df["TotalFamily"] <= 6), "FamilyGroup"] = "Large"
df = pd.get_dummies(df, columns=["FamilyGroup"])
from sklearn.feature_selection import mutual_info_classif

mi_scores = mutual_info_classif('YOUR DATAFRAME FEATURES', 'TARGET(SURVIVED)')
df
# df["TicketGroupSize"] = df.groupby("Ticket")["Ticket"].transform("count")
# df.groupby("TicketGroupSize")["Survived"].mean()
# df["TicketGroupSize"].value_counts()
# df.corr(numeric_only=True)

InvalidParameterError: The 'X' parameter of mutual_info_classif must be an array-like or a sparse matrix. Got 'YOUR DATAFRAME FEATURES' instead.

In [17]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Title_encoded
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Mr,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Mrs,5
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Mr,0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Mr,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Mrs,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,Mr,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,High Status,3
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,Mr,0
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,Mr,0
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,Master,2

In [18]:
test["CabinDeck"] = test["Cabin"].str[0]
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Title_encoded,CabinDeck
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Mr,0,NaN
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Mrs,5,NaN
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Mr,0,NaN
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Mr,0,NaN
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Mrs,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,Mr,0,NaN
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,High Status,3,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,Mr,0,NaN
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,Mr,0,NaN
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,Master,2,NaN